name: IRK GATEWAY CI/CD

on:
  push:
    branches: [main, reza]
  pull_request:
    branches: [main, reza]
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GATEWAY_HOST }}
          username: ${{ secrets.GATEWAY_USERNAME }}
          port: ${{ secrets.GATEWAY_PORT }}
          password: ${{ secrets.GATEWAY_PASSWORD }}
          script: |
            cd /var/www/APIGatewayIRK
            git fetch origin main
            git pull origin main
            php artisan config:cache
            php artisan route:clear
