name: IRK GATEWAY CI/CD

on:
  push:
    branches: [main, reza]
  pull_request:
    branches: [main, reza]
    
jobs:
  build:
    name: Check Code Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"
          tools: composer:v2
      - name: Copy env
        run: |
          cp .env ./var/www/APIGatewayIRK
      if: ${{ github.event_name == 'push' }}
      steps:
      - name: Deploy to ${{ secrets.GATEWAY_NAME }}
        if: github.ref == 'refs/heads/main'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GATEWAY_HOST }}
          username: ${{ secrets.GATEWAY_USERNAME }}
          port: ${{ secrets.GATEWAY_PORT }}
          password: ${{ secrets.GATEWAY_PASSWORD }}
          script: |
            cd /var/www/APIGatewayIRK
            git fetch origin main
            git pull origin main
            php artisan config:cache
            php artisan route:clear
